apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cicd-poc-prod

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml

images:
  - name: docker.io/hurtlinb/cicdpoc
    newTag: 2.2.0

patches:
  - path: replicas-patch.yaml
